### PR TITLE
use match.arg, message

### PR DESCRIPTION
**Pull request by shrektan**
thanks for the package. just think it's a better practice, if you don't mind.

### CODE REVIEW

**Comment by pzhaonet** [comment]
Thanks! match.arg() and message() are surely better. I am afraid that I have messed up the merging. This is the first pull request I've ever received!

**Comment by shrektan** [comment]
yes... the PR is closed without being merged.... :open_mouth:

**Comment by shrektan** [comment]
Don't  worry I've seen your commit. :rofl:

**Comment by pzhaonet** [comment]
I am sorry for that. I updated and synced the package first, and then saw your pull request. Then I wanted to merge, but found a conflict. I don't know what I did, but finally I merged the codes manually. Thank you for your understanding.

**Pull request closed without merging**
